### ISSUE TITLE
max_score useless in multimap symbols

### ISSUE THREAD

**Issue by slavkoja** [mailbaby/rspamd-rules#1]
AFAIK, the `max_score` is group option, not the symbol one. It seems to be silently ignored there in 2.7.

**Comment by mailbaby** [comment]
Thanks, confirmed. I have removed it in the latest update and will move this to groups.conf where it is working.

**Comment by slavkoja** [comment]
I am not using your rules nor maps/fuzzy, i only found it while i search inspiration ;-)

Thus i cannot test changes and IMO can be closed...
