### ISSUE TITLE
I am having a folder in local.d/blacklisted_ips in which there are multiple files containing malicious IPs. Is there anyway to include a directory containing multiple files in the map variable in multimap.conf instead of a specific filename like ip_bl.map

### ISSUE THREAD

**Issue by 1210315127** [mailbaby/rspamd-rules#2]
Dear all,

I am having a folder in local.d/blacklisted_ips in which there are multiple files containing malicious IPs.
Is there anyway to include a directory containing multiple files in the map variable in multimap.conf instead of a specific filename like ip_bl.map

Can I write like this for example? Please help me. Thank you. Main objective is to block all the files(they contain malicious ips list) under LOCAL_CONFDIR/local.d/blacklisted_ips directory.

local_bl_ip { type = "ip"; map = "$LOCAL_CONFDIR/local.d/blacklisted_ips"; symbol = "LOCAL_BL_IP"; description = "Local ip blacklist";score = 10;}

Does the above statement work?

**Comment by mailbaby** [comment]
I checked my own config and I have a map, then a metric for the score.

local_bl_ip { 
	type = "ip"; 
	map = "https://DOMAIN.com/local_bl_ip.map.inc"; 
	symbol = "LOCAL_BL_IP"; 
	description = "Local ip blacklist";
}


and the metric

symbol "LOCAL_BL_IP" {
    weight = 10.0;
    description = "Local Blocked IP";
}

**Comment by 1210315127** [comment]
Thank you for your response. Actually in the variable map I can see that
you are using a single file loclblip.map.inc
My requirement is that I have a directory with multiple  files containing
blacklisted ips
So how do we block that.
What you have told will definitely work for a single file. But I want to
give a directory containing multiple blacklistedips files.
So that all the files in the directory will be checked for blocking the ips.

Hope you got what i am trying to do

Thank you

**Comment by mailbaby** [comment]
I'm not sure multiple files are supported. That would be best sent to rspamd github. Personally I would run an RBL https://github.com/rspamd/rbldnsd to do this.

**Comment by 1210315127** [comment]
Thank you very much. Will try it out
