### ISSUE TITLE
Fuzzy hashes 0 ?

### ISSUE THREAD

**Issue by spec1re** [mailbaby/rspamd-rules#4]
Hi,

I've been using fuzzy.mailbaby.net:11335 for a while now, but since 1 - 2 months (maybe longer?), Fuzzy hashes is 0. Is the [fuzzy_check.conf](https://github.com/mailbaby/rspamd-rules/blob/main/local.d/fuzzy_check.conf) still valid?

![image](https://user-images.githubusercontent.com/11883076/227580426-2441b7ef-9dd3-4693-9fd9-6f843f50a0b5.png)

Nothing to find in the logs, even debug_modules  for fuzzy is on.

Any help is much appreciated. 

Regards

**Comment by JQuags** [comment]
Please confirm this is resolved on your system and you see something similar to

fuzzy_stored: 10976461

**Comment by JQuags** [comment]
I got confirmation via discord this is resolved from another user.

**Comment by spec1re** [comment]
Yes this is working fine again, thanks a bunch! 

![image](https://user-images.githubusercontent.com/11883076/228349103-3cd75abf-9158-4262-8daf-13985ff8462a.png)
